// JKR 30-day IG Stories / WA Status — 9:16 1080x1920. S01-S30.
// Video-scripted stories rendered as static keyframe (available-materials fallback); video upgrade flagged in index.
const PH = {
  H1: 'H1-SANY-breaker-Canggu-perbekel-action.jpg', H2: 'H2-SANY-bucket-ocean-Bali.jpg',
  H3: 'H3-SANY-fullside-branded-Bali.jpg', H4: 'H4-SANY-borpile-auger.jpg',
  H5: 'H5-Kubota-orange-clean-brand.jpg', H6: 'H6-Kubota-orange-portrait-clearing.jpg',
  H7: 'H7-Kubota-galian-fondasi-deep.jpg', H8: 'H8-FLEET-SANY-DumpTruk-lineup-branded.jpg',
  H9: 'H9-DumpTruk-JKR-Isuzu-branded.jpg', H10: 'H10-DumpTruk-timestamped-geo-proof.jpg',
  H11: 'H11-DumpTruk-coastal-excavator.jpg', H12: 'H12-SANY-workers-ocean-graffiti.jpg',
  H13: 'H13-SANY-breaker-worker-backshot.jpg', H14: 'H14-Kubota-worker-drainage.jpg',
};
const WA = '0877-8766-9088';
const S = (id, slide) => ({ id, kind: 'story', slides: [slide] });

export const stories = [
  S('S01', { type: 'cover', photo: PH.H8, badge: 'JUNI 2026',
    title: 'Juni baru. [[Proyek baru.]] Armada siap.',
    subtitle: 'Excavator besar, mini gang-sempit, dump truk + operator. Geser DM untuk slot Juni.',
    tags: ['SANY · KUBOTA · DUMP'], tagSolid: 'JKR · BALI' }),
  S('S02', { type: 'poll', eyebrow: 'POLL', title: 'Proyek kamu butuh unit yang mana?',
    options: [{ icon: '🟠', text: 'Kubota U30 — gang sempit / villa' }, { icon: '🟡', text: 'SANY 7 ton — galian besar / breaker' }, { icon: '⚪', text: 'Dump truk — angkut material' }],
    footerR: 'JAWAB DI POLL ↑' }),
  S('S03', { type: 'photoFull', photo: PH.H13, eyebrow: 'PAGI INI', title: 'Mobilisasi dimulai. 🌅',
    body: 'Tim & unit berangkat ke lokasi proyek. Operator SIO, alat terawat.', tags: ['BTS', 'TIM JKR'] }),
  S('S04', { type: 'photoFull', photo: PH.H8, eyebrow: 'DI FEED HARI INI', title: 'Kenal 3 unit JKR →',
    body: 'Carousel baru: SANY, Kubota U30, dump truk + attachment. Cek post terbaru.', tags: ['SWIPE UP', 'FEED'] }),
  S('S05', { type: 'photoFull', photo: PH.H1, eyebrow: 'VOLUME ON 🔊', title: 'SANY breaker hancurkan beton.',
    body: 'Bongkar struktur lama cepat & bersih — Kantor Perbekel, Canggu.', tags: ['BREAKER', 'DEMOLISI'] }),
  S('S06', { type: 'photoFull', photo: PH.H10, eyebrow: 'SEKALI JALAN', title: 'Dump truk 5m³ — 1 trip tuntas.',
    body: 'Tanah, pasir, batu, limbah konstruksi. Driver included.', tags: ['DUMP 5M³', 'DRIVER INCLUDED'] }),
  S('S07', { type: 'poll', eyebrow: 'QUIZ', title: 'Renovasi villa 200m² — pilih unit?',
    options: [{ icon: 'A', text: 'Kubota U30 (akses sempit)' }, { icon: 'B', text: 'SANY SY75C (volume besar)' }, { icon: 'C', text: 'Kombinasi keduanya' }],
    footerR: 'JAWABAN: C — TANYA KAMI' }),
  S('S08', { type: 'text', center: true, eyebrow: 'WEEKEND RECAP', title: 'Minggu ini di lapangan. 💪',
    body: 'Demolish, galian fondasi, cut & fill — beberapa proyek Bali Selatan tuntas. Terima kasih klien Juni!', aside: 'Slot minggu depan mulai dibuka.' }),
  S('S09', { type: 'text', center: true, eyebrow: 'EDUKASI', title: 'Breaker atau Bucket? 🤔',
    body: 'Salah pilih attachment = waste budget. Besok kami bahas tuntas di feed.', aside: 'Bucket = gali · Breaker = hancur.' }),
  S('S10', { type: 'photoFull', photo: PH.H1, eyebrow: 'DI FEED HARI INI', title: 'Breaker vs Bucket — kapan pakai →',
    body: 'Carousel edukasi baru. Biar nggak salah pesan attachment.', tags: ['SWIPE UP', 'FEED'] }),
  S('S11', { type: 'photoFull', photo: PH.H4, eyebrow: 'JARANG TERLIHAT', title: 'Setup borpile pagi ini. 🌀',
    body: 'Auger attachment SANY — drill fondasi tiang dalam. Layanan langka di Bali.', tags: ['BORPILE', 'RARE'] }),
  S('S12', { type: 'photoFull', photo: PH.H7, eyebrow: 'PRESISI', title: 'Galian rapi, dinding bersih.',
    body: 'Bucket Kubota U30 — fondasi & saluran presisi di lahan terbatas.', tags: ['BUCKET', 'KUBOTA U30'] }),
  S('S13', { type: 'testimonial', eyebrow: 'TESTIMONI', quote: 'Sangat bisa diandalkan, respon admin cepat, alat-alat baru, profesional handal. Harga bersahabat. Suksme sudah dibantu!',
    name: 'Dana Natawiguna', role: 'Local Guide · 236 ulasan', footerR: '4,9★ · 68 ULASAN' }),
  S('S14', { type: 'photoFull', photo: PH.H14, eyebrow: 'SAFETY FIRST', title: 'Komunikasi tim = kerja aman.',
    body: 'Hand-signal operator & ground crew — presisi tanpa kompromi keselamatan.', tags: ['TIM', 'SIO OPERATOR'] }),
  S('S15', { type: 'text', center: true, eyebrow: 'TIPS KONTRAKTOR', title: '3 hal cek sebelum sewa alat.',
    body: '1. Akses lokasi (lebar gang).\n2. Volume & jenis material.\n3. Rental kredibel — pemilik langsung + invoice.', aside: 'Survey gratis bantu pastikan semua.' }),
  S('S16', { type: 'photoFull', photo: PH.H6, eyebrow: 'USP JKR', title: 'Gang 1,55 m? Kubota lewat. 🚜',
    body: 'Lebar unit 1,6m + zero tail swing — masuk akses villa yang lain harus reroute.', tags: ['LEBAR 1,6 M', 'BALI SELATAN'] }),
  S('S17', { type: 'photoFull', photo: PH.H12, eyebrow: 'LIVE ON-SITE', title: 'Hari ini di Canggu. 📍',
    body: 'Land clearing dekat pantai — tim JKR on the ground.', tags: ['CANGGU', 'ON-SITE'] }),
  S('S18', { type: 'photoFull', photo: PH.H7, eyebrow: 'BEFORE → AFTER', title: 'Lahan villa siap fondasi. ✨',
    body: 'Dari bongkaran kasar ke lahan level. “Cocok untuk pekerjaan tanah & pondasi.” — Jiva Loft Villa.', tags: ['VILLA', 'CANGGU'] }),
  S('S19', { type: 'text', center: true, eyebrow: 'AREA SERVICE', title: '9 kabupaten Bali, base di Canggu.',
    body: 'Badung · Denpasar · Tabanan · Gianyar · Buleleng · Bangli · Karangasem · Klungkung · Jembrana.', aside: 'Respon tercepat untuk Bali Selatan.' }),
  S('S20', { type: 'testimonial', eyebrow: 'TESTIMONI · EXPAT', quote: 'Canggu-based excavator rental making the service quick — no need to mobilize heavy equipment from far away. The price is reasonable and the operator is reliable.',
    name: 'Krishna Chieppa', role: 'Local Guide · 90 reviews', footerR: '4.9★ · 68 REVIEWS' }),
  S('S21', { type: 'text', center: true, eyebrow: 'WEEKEND', title: 'Tim recharge — Senin siap lagi. 🔋',
    body: 'Akhir pekan untuk maintenance unit & istirahat tim. Slot minggu depan dibuka.', aside: 'Booking awal = jadwal lebih pasti.' }),
  S('S22', { type: 'photoFull', photo: PH.H13, eyebrow: 'TIM JKR', title: 'Tim JKR siap untuk proyek Anda.',
    body: 'Pemilik langsung + operator SIO berpengalaman. Bertanggung jawab dari survey sampai selesai.', tags: ['PEMILIK LANGSUNG', 'SIO'] }),
  S('S23', { type: 'text', center: true, eyebrow: 'CARA SEWA', title: 'Sewa di JKR — 4 langkah.',
    body: '1. Chat WA + ceritakan proyek.\n2. Survey lokasi gratis.\n3. Quote transparan + jadwal.\n4. Mobilisasi unit + operator.', aside: '“Bisa konsultasi dulu, tidak dipaksa order.” — Rika A.' }),
  S('S24', { type: 'poll', eyebrow: 'TANYA KAMI', title: 'Ada pertanyaan soal proyek Anda?',
    options: [{ icon: '💬', text: 'Unit mana yang cocok?' }, { icon: '🗺️', text: 'Bisa survey area saya?' }, { icon: '🧾', text: 'Minta estimasi proyek' }],
    footerR: 'DM / WA ' + WA }),
  S('S25', { type: 'photoFull', photo: PH.H3, eyebrow: 'BRAND STORY', title: 'Dibangun proyek demi proyek.',
    body: 'Dari Canggu untuk Bali — alat berat yang bisa diandalkan, dikelola pemilik langsung.', tags: ['JKR', 'SINCE BALI'] }),
  S('S26', { type: 'text', center: true, eyebrow: 'NUMBERS JUNI', title: '4,9★ dari [[68 ulasan]] Google.',
    body: 'Dipercaya kontraktor, arsitek & pemilik villa di 9 kabupaten Bali. Terima kasih sudah merekomendasikan JKR.', aside: 'Reputasi nyata, bukan klaim.' }),
  S('S27', { type: 'testimonial', eyebrow: 'TESTIMONI · VILLA', quote: 'Unit selalu dalam kondisi bagus, operator berpengalaman, tim support responsif. Harga bersaing dan proses sewa transparan.',
    name: 'Jiva Loft Style Villa Canggu', role: 'Pemilik Villa · Google Review', footerR: '4,9★ · 68 ULASAN' }),
  S('S28', { type: 'photoFull', photo: PH.H8, eyebrow: 'THROWBACK JUNI', title: 'Armada lengkap, satu tim.',
    body: 'Momen favorit Juni — SANY, dump truk & Kubota kerja bareng di lapangan.', tags: ['RECAP', 'JUNI 2026'] }),
  S('S29', { type: 'text', center: true, eyebrow: 'TERIMA KASIH', title: 'Terima kasih, Juni! 🙏',
    body: 'Setiap proyek, setiap kepercayaan — kami hargai. Sampai jumpa di proyek Juli Anda.', aside: 'Pemilik langsung · JKR Bali.' }),
  S('S30', { type: 'cta', title: 'Booking Juli sudah dibuka. 📅',
    body: 'Amankan slot unit + operator untuk proyek Juli Anda. Survey lokasi gratis, konsultasi dulu.',
    wa: WA, tags: ['SLOT JULI', 'SURVEY GRATIS'] }),
];
